### ISSUE TITLE
Failed template steps are not represented in errors

### ISSUE THREAD

**Issue by eugs** [qavajs/template#12]
It is hard to debug **templates**: no clear picture on which exact step the template is failing

For example:
"**I login**" is a template step, if there are several wait steps inside we have no information on which one is timed out

<img width="807" alt="image" src="https://user-images.githubusercontent.com/29432117/206209110-49136cb2-0cb9-448b-a1b5-22ea9e656bb1.png">

**Comment by AlexGalichenko** [comment]
will be fixed in 0.0.4
