### ISSUE TITLE
Templates used twice in another template substitute the wrong data

### ISSUE THREAD

**Issue by eugs** [qavajs/template#15]
Assume we have a template  **When I set <year> year**
If we: 

- put it into another template, say **When I set all dates**
- call **When I set <year> year** twice with <year1> and <year2> values
- then only **first** value will be putted inside a both calls

\<year1\> = 2019
\<year2\> = 2020

```
...
When I set <year1> year // will set 2019
...
When I set <year2> year => will set 2019 again instead of 2020
```

Problem in code might be in here inside of `reduce `

<img width="938" alt="image" src="https://user-images.githubusercontent.com/29432117/212324575-c6f96a30-6fe0-4d57-938e-cb9b71b54d35.png">

**Comment by AlexGalichenko** [comment]
Fixed in 0.0.5
